version: 2.1

orbs:
   win: circleci/windows@1.0.0

workflows:
  test:
    jobs:
      - test-linux:
          name: Python 3.8
          docker-image: cimg/python:3.8
     

jobs:
  test-linux:
    parameters:
      docker-image:
        type: string
      test-packaging:
        type: boolean
        default: true
      test-with-codeclimate:
        type: boolean
        default: false
      test-with-mypy:
        type: boolean
        default: true
      skip-sse-contract-tests:
        type: boolean
        default: false
    docker:
      - image: <<parameters.docker-image>>
      - image: redis
      - image: amazon/dynamodb-local
      - image: consul
    steps:
      - checkout
      - run:
          name: install requirements
          command: |
            pip install -r test-requirements.txt;
            pip install -r test-filesource-optional-requirements.txt;
            pip install -r consul-requirements.txt;
            python setup.py install;
            pip freeze
      - when:
          condition: <<parameters.test-with-codeclimate>>
          steps:
            - run:
                name: run tests (with CodeClimate)
                command: |
                  mkdir test-reports
                  pytest -s --cov=ldclient --junitxml=test-reports/junit.xml testing -W error::SyntaxWarning
                  sh -c '[ -n "${CODECLIMATE_REPO_TOKEN+1}" ] && codeclimate-test-reporter || echo "No CODECLIMATE_REPO_TOKEN value is set; not publishing coverage report"'
      - unless:
          condition: <<parameters.test-with-codeclimate>>
          steps:
            - run:
                name: run tests
                command: |
                  mkdir test-reports
                  pytest -s --junitxml=test-reports/junit.xml testing -W error::SyntaxWarning
      - when:
          condition: <<parameters.test-packaging>>
          steps:
            - run:
                name: test packaging/install
                command: |
                  sudo rm -rf dist *.egg-info
                  ./test-packaging/test-packaging.sh
      - when:
          condition: <<parameters.test-with-mypy>>
          steps:
            - run:
                name: verify typehints
                command: |
                  export PATH="/home/circleci/.local/bin:$PATH"
                  make lint
      - unless:
          condition: <<parameters.skip-sse-contract-tests>>
          steps:
          - run:
              name: build SSE contract test service
              command: cd sse-contract-tests && make build-test-service
          - run:
              name: start SSE contract test service
              command: cd sse-contract-tests && make start-test-service
              background: true
          - run:
              name: run SSE contract tests
              command: cd sse-contract-tests && make run-contract-tests

      - run: make build-contract-tests
      - run:
          command: make start-contract-test-service
          background: true
      - run:
          name: run contract tests
          command: TEST_HARNESS_PARAMS="-junit test-reports/contract-tests-junit.xml" make run-contract-tests

      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
